export const categories = [
    {
        id: 1,
        name: "Avil Milk",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails: [
            {id:"NormalAvil", itemsName: "NrmlAvilMilk", rate:30, bgColor: "bg-[#908172]", fgColor: "bg-[#696353]", brdr:"border-[#696353]", textColor:"text-[#696353]"},
            {id:"FruitAvil", itemsName: "FruitAvil", rate:35, bgColor: "bg-[#908172]", fgColor: "bg-[#696353]", brdr:"border-[#696353]", textColor:"text-[#696353]"},
            {id:"SpAvil", itemsName: "AvilSp", rate:45, bgColor: "bg-[#908172]", fgColor: "bg-[#696353]", brdr:"border-[#696353]", textColor:"text-[#696353]"},
            {id:"SpBoostAvil", itemsName: "AvilBoostSp", rate:45, bgColor: "bg-[#908172]", fgColor: "bg-[#696353]", brdr:"border-[#696353]", textColor:"text-[#696353]"},
            {id:"PinappleAvil", itemsName: "Pinapple", rate:60, bgColor: "bg-yellow-500", fgColor: "bg-[#a37d06]", brdr:"border-[#a37d06]", textColor:"text-[#a37d06]"},
            {id:"WaterMelonAvil", itemsName: "WaterMelon", rate:60, bgColor: "bg-red-500", fgColor: "bg-[#a52d2e]", brdr:"border-[#a52d2e]", textColor:"text-[#a52d2e]"},
            {id:"RoseAvil", itemsName: "Rose", rate:60, bgColor: "bg-pink-500", fgColor: "bg-[#aa346f]", brdr:"border-[#aa346f]", textColor:"text-[#aa346f]"},
            {id:"CaramelAvil", itemsName: "Caramel", rate:70, bgColor: "bg-[#A97D48]", fgColor: "bg-[#765834]", brdr:"border-[#765834]", textColor:"text-[#765834]"},
            {id:"WonderJoyAvil", itemsName: "WonderJoy", rate:70, bgColor: "bg-[#D3B1F7]", fgColor: "bg-[#967eb1]", brdr:"border-[#967eb1]", textColor:"text-[#967eb1]"},
            {id:"ChikkuAvil", itemsName: "Chikku", rate:70, bgColor: "bg-[#5d501e]", fgColor: "bg-[#a48d38]", brdr:"border-[#a48d38]", textColor:"text-[#a48d38]"},
            {id:"KiwiAvil", itemsName: "Kiwi", rate:65, bgColor: "bg-[#BDB76B]", fgColor: "bg-[#6d6a3f]", brdr:"border-[#6d6a3f]", textColor:"text-[#6d6a3f]"},
            {id:"MangoAvil", itemsName: "Mango", rate:60, bgColor: "bg-orange-500", fgColor: "bg-[#b75614]", brdr:"border-[#b75614]", textColor:"text-[#b75614]"},
            {id:"PistaAvil", itemsName: "Pista", rate:65, bgColor: "bg-[#C4D6A3]", fgColor: "bg-[#8a9773]", brdr:"border-[#8a9773]", textColor:"text-[#8a9773]"},
            {id:"PaladaAvil", itemsName: "Palada", rate:70, bgColor: "bg-[#D4AF37]", fgColor: "bg-[#9f842c]", brdr:"border-[#9f842c]", textColor:"text-[#9f842c]"},
            {id:"ColdCoffeAvil", itemsName: "ColdCoffe", rate:60, bgColor: "bg-[#6f4747]", fgColor: "bg-[#312020]", brdr:"border-[#312020]", textColor:"text-[#312020]"},
            {id:"StrawberryAvil", itemsName: "Strawberry", rate:65, bgColor: "bg-[#ab1d23]", fgColor: "bg-[#cf272f]", brdr:"border-[#cf272f]", textColor:"text-[#cf272f]"},
            {id:"ChoconutAvil", itemsName: "Choconut", rate:70, bgColor: "bg-[#006400]", fgColor: "bg-[#23a103]", brdr:"border-[#23a103]", textColor:"text-[#23a103]"},
            {id:"ChocolateAvil", itemsName: "Chocolate", rate:80, bgColor: "bg-[#FFF8DC]", fgColor: "bg-[#a79d84]", brdr:"border-[#a79d84]", textColor:"text-[#a79d84]"},
            {id:"MalgoaNutAvil", itemsName: "MalgoaNut", rate:90, bgColor: "bg-[#8B4513]", fgColor: "bg-[#723c0e]", brdr:"border-[#723c0e]", textColor:"text-[#723c0e]"},
            {id:"FruitsAvil", itemsName: "Fruits&Nuts", rate:75, bgColor: "bg-[#FFF8DC]", fgColor: "bg-[#E6C9A2]", brdr:"border-[#E6C9A2]", textColor:"text-[#E6C9A2]"},
            {id:"NutMixAvil", itemsName: "NutMix", rate:75, bgColor: "bg-[#FFD700]", fgColor: "bg-[#a68c02]", brdr:"border-[#a68c02]", textColor:"text-[#a68c02]"},
            {id:"RoyalAvil", itemsName: "Royal", rate:70, bgColor: "bg-[#692e2e]", fgColor: "bg-[#a64a40]", brdr:"border-[#a64a40]", textColor:"text-[#a64a40]"},
            {id:"BadamAvilAvil", itemsName: "BadamAvil", rate:80, bgColor: "bg-[#C99A6B]", fgColor: "bg-[#A97D48]", brdr:"border-[#A97D48]", textColor:"text-[#312020]"},
            {id:"OreoAvil", itemsName: "Oreo", rate:80, bgColor: "bg-[#312020]", fgColor: "bg-[#7b5240]", brdr:"border-[#7b5240]", textColor:"text-[#7b5240]"},
            {id:"ChocoPieAvil", itemsName: "ChocoPie", rate:90, bgColor: "bg-[#E6C9A2]", fgColor: "bg-[#ab8d63]", brdr:"border-[#ab8d63]", textColor:"text-[#ab8d63]"},
            {id:"ItalianDelightAvil", itemsName: "ItalianDelight", rate:85, bgColor: "bg-[#8FBC8F]", fgColor: "bg-[#5f7a5c]", brdr:"border-[#5f7a5c]", textColor:"text-[#5f7a5c]"},
            {id:"AfghaniAvil", itemsName: "Afghani", rate:90, bgColor: "bg-[#69642e]", fgColor: "bg-[#3c3a1d]", brdr:"border-[#3c3a1d]", textColor:"text-[#3c3a1d]"},
            {id:"BhoomBoomAvil", itemsName: "BhoomBoom", rate:100, bgColor: "bg-red-500", fgColor: "bg-[#a83131]", brdr:"border-[#a83131]", textColor:"text-[#a83131]"},
            {id:"NeuttelaAvil", itemsName: "Neuttela", rate:90, bgColor: "bg-[#A5743C]", fgColor: "bg-[#6d4e2a]", brdr:"border-[#6d4e2a]", textColor:"text-[#6d4e2a]"},
            {id:"SnickersAvil", itemsName: "Snickers", rate:80, bgColor: "bg-[#3b3b3b]", fgColor: "bg-[#6e6e6f]", brdr:"border-[#6e6e6f]", textColor:"text-[#6e6e6f]"},
            {id:"FigAvil", itemsName: "Fig&Honey", rate:120, bgColor: "bg-[#C99A6B]", fgColor: "bg-[#816346]", brdr:"border-[#816346]", textColor:"text-[#816346]"},
            {id:"DryFruitAvil", itemsName: "DryFruit", rate:120, bgColor: "bg-[#D3CDB0]", fgColor: "bg-[#95927e]", brdr:"border-[#95927e]", textColor:"text-[#95927e]"},
            {id:"SpecialNutsAvil", itemsName: "SpecialNuts", rate:120, bgColor: "bg-[#2b3940]", fgColor: "bg-[#405d6f]", brdr:"border-[#405d6f]", textColor:"text-[#405d6f]"},
            {id:"KitkatAvil", itemsName: "KitKatAvil", rate:80, bgColor: "bg-[#544535]", fgColor: "bg-[#7c6d47]", brdr:"border-[#7c6d47]", textColor:"text-[#7c6d47]"},
            {id:"TendrCoconutAvil", itemsName: "TndrCoconut", rate:90, bgColor: "bg-[#006400]", fgColor: "bg-[#23a103]", brdr:"border-[#23a103]", textColor:"text-[#23a103]"},
            {id:"SpanishDelightAvil", itemsName: "SpanishDelight", rate:75, bgColor: "bg-[#DC143C]", fgColor: "bg-[#a10e2b]", brdr:"border-[#a10e2b]", textColor:"text-[#a10e2b]"},
            {id:"ButterSchotchAvil", itemsName: "ButterSchotch", rate:60, bgColor: "bg-red-300", fgColor: "bg-[#af7373]", brdr:"border-[#af7373]", textColor:"text-[#af7373]"},
            {id:"HCombMouldAvil", itemsName: "HCombMould", rate:80, bgColor: "bg-[#FFD700]", fgColor: "bg-[#a58b02]", brdr:"border-[#a58b02]", textColor:"text-[#a58b02]"},
            {id:"LeBananadAvil", itemsName: "LeBananaSp", rate:140, bgColor: "bg-[#a88e02]", fgColor: "bg-[#e0be04]", brdr:"border-[#e0be04]", textColor:"text-[#e0be04]"},            
          ]  
    },
    {
        id: 2,
        name: "Mocktail Shake",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails: [
            { id:"SharjahShake", itemsName: "Sharjah", rate:60, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"SaudiShake", itemsName: "Saudi", rate:60, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"ChikuShake", itemsName: "Chiku", rate:60, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"mangoShake", itemsName: "mango", rate:70, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"GrapeShake", itemsName: "Grape", rate:70, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"AppleShake", itemsName: "Apple", rate:70, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"KiwiShake", itemsName: "Kiwi", rate:70, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"ShamamShake", itemsName: "Shamam", rate:70, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"AnarShake", itemsName: "Anar", rate:80, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"avacadoShake", itemsName: "avacado", rate:80, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"StrawberryShake", itemsName: "Strawberry", rate:70, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"vanilaShake", itemsName: "vanila", rate:70, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"PistaShake", itemsName: "Pista", rate:70, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"PeanutButrShake", itemsName: "PeanutButter", rate:70, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"HocusPocusShake", itemsName: "HocusPocus", rate:80, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"DryFruitShake", itemsName: "DryFruit", rate:80, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"FigHoneyShake", itemsName: "FigAndHoney", rate:80, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"CashAlmndShake", itemsName: "CashewAlmond", rate:800, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"OreoShake", itemsName: "Oreo", rate:70, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"SnickersShake", itemsName: "Snickers", rate:70, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"FiveStarShake", itemsName: "FiveStar", rate:70, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"CadberryShake", itemsName: "Cadberry", rate:70, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"KitkatChocoShake", itemsName: "KitkatChocolate", rate:70, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"BelgiumChocoShake", itemsName: "BelgiumChocolate", rate:70, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"DarkFantasyShake", itemsName: "DarkFantasy", rate:90, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"NutellaShakes", itemsName: "NutellaShakes", rate:10, bgColor: "bg-red-500", fgColor: "bg-red-700" },
          ]
    },
    {
        id: 3,
        name: "Tender Special",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails: [
            { id:"TenderCocunutSp", itemsName: "TenderCocunut", rate:70, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"TenderVannilaSp", itemsName: "TenderVannila", rate:70, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"TenderBoostSp", itemsName: "TenderBoost", rate:70, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"TenderChikkuSp", itemsName: "TenderChikku", rate:70, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"TenderPistaSp", itemsName: "TenderPista", rate:80, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"TenderOreoSp", itemsName: "TenderOreo", rate:80, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"TenderCashewSp", itemsName: "TenderCashew", rate:80, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"TenderDatesSp", itemsName: "TenderDates", rate:90, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"TenderDryFriutSp", itemsName: "TenderDryFriut", rate:90, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"TenderSpecielSp", itemsName: "TenderSpeciel", rate:10, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
           ]
    },
    {
        id: 4,
        name: "Mud Shakes",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails: [
            { id:"ChoclateMud", itemsName: "ChoclateMud", rate:95, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"HocusPocusMud", itemsName: "HocusPocusMud", rate:95, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"OreoCrumbleMud", itemsName: "OreoCrumble", rate:90, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"RockyChikkuMud", itemsName: "RockyChikku", rate:90, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"PeanutMud", itemsName: "PeanutMud", rate:90, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"FriutMud", itemsName: "FriutMud", rate:90, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"5StarMud", itemsName: "5StarMud", rate:95, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"SnickersMud", itemsName: "SnickersMud", rate:95, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"KitkatMud", itemsName: "KitkatMud", rate:95, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"CadberryMud", itemsName: "Cadberry", rate:95, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"PistaMud", itemsName: "PistaMud", rate:95, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"MississippiMud", itemsName: "MississippiMud", rate:110, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"FigAndHoneyMud", itemsName: "FigAndHoneyMud", rate:110, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"CashewMud", itemsName: "CashewMud", rate:110, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"DryFriutmud", itemsName: "DryFriutmud", rate:110, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"NuttellaMud", itemsName: "NuttellaMud", rate:120, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"HiBigBubblesMud", itemsName: "HighBigBubbles", rate:160, bgColor: "bg-red-500", fgColor: "bg-red-700" },
          ]
    },
    {
        id: 6,
        name: "Fresh Juice",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails: [
            { id:"orangeFj", itemsName: "orange", rate:60, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"AppleFj", itemsName: "Apple", rate:60, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"GrapesFj", itemsName: "Grapes", rate:60, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"ShamamFj", itemsName: "Shamam", rate:60, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"MussambiFj", itemsName: "Mussambi", rate:60, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"PineappleFj", itemsName: "Pineapple", rate:60, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"MangoFj", itemsName: "Mango", rate:60, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"waterMelonFj", itemsName: "waterMelon", rate:60, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"AnarFj", itemsName: "Anar", rate:70, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"PappayaFj", itemsName: "Pappaya", rate:60, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            ]
        },
    {
        id: 7,
        name: "Lime",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails:[
            { id:"FreshLime", itemsName: "FreshLime", rate:20, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"MintLime", itemsName: "MintLime", rate:30, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"GingerLime", itemsName: "GingerLime", rate:30, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"pineappleLime", itemsName: "pineappleLime", rate:30, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"GrapeLime", itemsName: "GrapeLime", rate:30, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"OrangeLime", itemsName: "OrangeLime", rate:30, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
        ]
    },
    // {
    //     id: 8,
    //     name: "Sodas",
    //     bg: "bg-[#007BFF]",
    //     fg: "text-black-600"
    // },
    {
        id: 9,
        name: "Mojitos",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails: [
            { id:"BleedBlueMj", itemsName: "BleedBlue", rate:70, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"PassionFriutMj", itemsName: "PassionFriut", rate:70, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"GreenAppleMj", itemsName: "GreenApple", rate:70, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"StrawberryMj", itemsName: "Strawberry", rate:70, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"OrangeMj", itemsName: "Orange", rate:70, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"GuavaMj", itemsName: "Guava", rate:70, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"KiwiMj", itemsName: "Kiwi", rate:70, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
        ]
    },
    {
        id: 10,
        name: "Malva",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails:[
            {id:"BananaMalva", itemsName: "BananaMalva", rate:90, bgColor: "bg-[#FFD700]", fgColor: "bg-[#a68c02]", brdr:"border-[#a68c02]", textColor:"text-[#a68c02]"},
            {id:"ChikkuMalva", itemsName: "ChikkuMalva", rate:90, bgColor: "bg-[#DC143C]", fgColor: "bg-[#a10e2b]", brdr:"border-[#a10e2b]", textColor:"text-[#a10e2b]"},
            {id:"MangoMalva", itemsName: "MangoMalva", rate:100, bgColor: "bg-[#692e2e]", fgColor: "bg-[#a64a40]", brdr:"border-[#a64a40]", textColor:"text-[#a64a40]"},
            {id:"Avacadomalva", itemsName: "Avacadomalva", rate:100, bgColor: "bg-[#C99A6B]", fgColor: "bg-[#A97D48]", brdr:"border-[#A97D48]", textColor:"text-[#312020]"},
           
        ]
    },
    {
        id: 11,
        name: "Cold Coffee",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails:[
            {id:"HardRockCF", itemsName: "HardRockCoffee", rate:70, bgColor: "bg-[#006400]", fgColor: "bg-[#23a103]", brdr:"border-[#23a103]", textColor:"text-[#23a103]"},
            {id:"StrawberryCF", itemsName: "StrawberryCoffee", rate:70, bgColor: "bg-[#FFF8DC]", fgColor: "bg-[#a79d84]", brdr:"border-[#a79d84]", textColor:"text-[#a79d84]"},
            {id:"ChocolateCF", itemsName: "ChocolateCoffee", rate:70, bgColor: "bg-[#8B4513]", fgColor: "bg-[#723c0e]", brdr:"border-[#723c0e]", textColor:"text-[#723c0e]"},
            {id:"MudCF", itemsName: "MudCoffee", rate:90, bgColor: "bg-[#FFF8DC]", fgColor: "bg-[#E6C9A2]", brdr:"border-[#E6C9A2]", textColor:"text-[#E6C9A2]"},
         
        ]
    },
    {
        id: 12,
        name: "Ice Cream",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails:[
            {id:"FriutOurLoadSpIC", itemsName: "FrtOurLdSp", rate:110, bgColor: "bg-[#006400]", fgColor: "bg-[#23a103]", brdr:"border-[#23a103]", textColor:"text-[#23a103]"},
            {id:"GudBudIC", itemsName: "GudBud", rate:130, bgColor: "bg-[#FFF8DC]", fgColor: "bg-[#a79d84]", brdr:"border-[#a79d84]", textColor:"text-[#a79d84]"},  
            {id:"VanilaIC", itemsName: "Vanila", rate:25, bgColor: "bg-[#f3e5ab]", fgColor: "bg-[#a29871]", brdr:"border-[#a29871]", textColor:"text-[#a29871]"},  
            {id:"PistaIC", itemsName: "Pista", rate:30, bgColor: "bg-[#DAF7A6]", fgColor: "bg-[#a4b97e]", brdr:"border-[#a4b97e]", textColor:"text-[#a4b97e]"},  
            {id:"StrBerryIceIC", itemsName: "Strawberry", rate:30, bgColor: "bg-[#de859f]", fgColor: "bg-[#9e6173]", brdr:"border-[#9e6173]", textColor:"text-[#9e6173]"},  
            {id:"ButrSchotchIC", itemsName: "ButrSchotch", rate:30, bgColor: "bg-[#d4d785]", fgColor: "bg-[#9d9f64]", brdr:"border-[#9d9f64]", textColor:"text-[#9d9f64]"},  
            {id:"ChocolateIC", itemsName: "Chocolate", rate:30, bgColor: "bg-[#514548]", fgColor: "bg-[#7d6a6f]", brdr:"border-[#7d6a6f]", textColor:"text-[#7d6a6f]"},  
            {id:"TenderIC", itemsName: "Tender", rate:40, bgColor: "bg-[#cefead]", fgColor: "bg-[#9cc182]", brdr:"border-[#9cc182]", textColor:"text-[#9cc182]"},  
            {id:"SpanishIC", itemsName: "Spanish", rate:40, bgColor: "bg-[#97c7f0]", fgColor: "bg-[#7197b6]", brdr:"border-[#7197b6]", textColor:"text-[#7197b6]"},  
            {id:"MangoIC", itemsName: "Mango", rate:40, bgColor: "bg-[#e3e989]", fgColor: "bg-[#b0b46b]", brdr:"border-[#b0b46b]", textColor:"text-[#b0b46b]"},  
            {id:"BlueBryIC", itemsName: "BlueBerry", rate:50, bgColor: "bg-[#67cbf5]", fgColor: "bg-[#5f98b0]", brdr:"border-[#5f98b0]", textColor:"text-[#5f98b0]"},  
       
        ]
    },
    {
        id: 13,
        name: "Falooda",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails:[
            { id:"FrtSldWithIceCream", itemsName: "FriutSaladWithIceCream", rate:70, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"NormalFlda", itemsName: "NormalFalooda", rate:90, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"MangoDreamFlda", itemsName: "MangoDreamFalooda", rate:110, bgColor: "bg-red-300", fgColor: "bg-red-700" },
            { id:"StrberryDreamFlda", itemsName: "StrawberryDreamFalooda", rate:110, bgColor: "bg-orange-500", fgColor: "bg-orange-700" },
            { id:"ZaharFlda", itemsName: "ZaharFalooda", rate:110, bgColor: "bg-pink-500", fgColor: "bg-pink-700" },
            { id:"LeBananSpecialFlda", itemsName: "LeBananSpecialFalooda", rate:140, bgColor: "bg-[#6f4747]", fgColor: "bg-[#6f4747]" },
            { id:"TenderCocunutFlda", itemsName: "TenderCocunutFalooda", rate:130, bgColor: "bg-yellow-500", fgColor: "bg-yellow-700" },
            { id:"RoyalFlda", itemsName: "RoyalFalooda", rate:130, bgColor: "bg-red-500", fgColor: "bg-red-700" },
            { id:"DryFriutFlda", itemsName: "DryFriutFalooda", rate:140, bgColor: "bg-red-300", fgColor: "bg-red-700" },
   ]
    },
    {
        id: 14,
        name: "Chocolate",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails:[
            {id:"ChocolateFudge", itemsName: "ChocolateFudge", rate:70, bgColor: "bg-[#FFD700]", fgColor: "bg-[#a68c02]", brdr:"border-[#a68c02]", textColor:"text-[#a68c02]"},
            {id:"brownieWithIceCream", itemsName: "brownieWithIceCream", rate:110, bgColor: "bg-[#DC143C]", fgColor: "bg-[#a10e2b]", brdr:"border-[#a10e2b]", textColor:"text-[#a10e2b]"},
            {id:"DryFriutSundae", itemsName: "DryFriutSundae", rate:100, bgColor: "bg-[#692e2e]", fgColor: "bg-[#a64a40]", brdr:"border-[#a64a40]", textColor:"text-[#a64a40]"},
            {id:"CandyCrash", itemsName: "CandyCrash", rate:100, bgColor: "bg-[#C99A6B]", fgColor: "bg-[#A97D48]", brdr:"border-[#A97D48]", textColor:"text-[#312020]"},
            {id:"CookiesAndCream", itemsName: "CookiesAndCream", rate:80, bgColor: "bg-[#FFD700]", fgColor: "bg-[#a68c02]", brdr:"border-[#a68c02]", textColor:"text-[#a68c02]"},
           
        ]
    },
    {
        id: 15,
        name: "Soda",
        bg: "bg-[#007BFF]",
        fg: "text-black-600",
        itemsDetails:[
            {id:"SodaSlt", itemsName: "Salt Soda", rate:20, bgColor: "bg-[#FFD700]", fgColor: "bg-[#a68c02]", brdr:"border-[#a68c02]", textColor:"text-[#a68c02]"},
            {id:"SodaGrp", itemsName: "Grape Soda", rate:30, bgColor: "bg-[#DC143C]", fgColor: "bg-[#a10e2b]", brdr:"border-[#a10e2b]", textColor:"text-[#a10e2b]"},
            {id:"SodaChly", itemsName: "Chilly Soda", rate:30, bgColor: "bg-[#692e2e]", fgColor: "bg-[#a64a40]", brdr:"border-[#a64a40]", textColor:"text-[#a64a40]"},
            {id:"GrApplSoda", itemsName: "GreenApple Soda", rate:30, bgColor: "bg-[#C99A6B]", fgColor: "bg-[#A97D48]", brdr:"border-[#A97D48]", textColor:"text-[#312020]"},
            {id:"PinappleSoda", itemsName: "Pinapple Soda", rate:30, bgColor: "bg-[#FFD700]", fgColor: "bg-[#a68c02]", brdr:"border-[#a68c02]", textColor:"text-[#a68c02]"},
           
        ]
    }
];
